data:
  raw_input_dir: data/raw_input/
  raw_input_file: Concrete_Data.csv
test:
  output_dir: logs/test_output/
experiment:
  outputs_dir: experiments/outputs/
  configs_dir: experiments/configs/
  scripts_dir: experiments/scripts/
runtime:
  output_dir: logs/runtime/